### PR TITLE
Fixed builds for latest Bevy git

### PR DESCRIPTION
**Pull request by billyb2**
Just replaced all the AppBuilder stuff with App, so that the library would build on the latest version of Bevy.

Related to #35

### CODE REVIEW

**Comment by billyb2** [comment]
Hey @smokku, not to be annoying, but any updates on merging this PR?

**Comment by smokku** [comment]
> Hey @smokku, not to be annoying, but any updates on merging this PR?

As soon as new Bevy gets released.

Merging it now would break `master` for everyone using Bevy release.

**Comment by billyb2** [comment]
Oh okay, I totally understand

**Comment by woelper** [comment]
Hi! First of all thanks for this great library and the PR - now that bevy 0.6 is on crates.io, would it make sense to merge this to `master` now?

**Comment by billyb2** [comment]
I'd definetly be interested in merging if @smokku would

**Comment by smokku** [comment]
Fixed by #42

**Pull request closed without merging**
