### PR TITLE
Channels wasm

### PR DESCRIPTION
**Pull request by johnpmayer**
This is in a pretty crappy state to start. Next steps:

- [ ] Get a cross-platform now() - it fails on wasm
- [ ] Refactor channels-server and channels-client; it's getting to be too many macros
- [ ] Only use WebGL2 backend on wasm target

Also i'm a bit of a dumbshit on one particular aspect - what's the point of find_my_ip_address?

### CODE REVIEW

**Comment by smokku** [comment]
> Also i'm a bit of a dumbshit on one particular aspect - what's the point of find_my_ip_address?

Client needs to know the address of the server to connect to.
In case of example it gets the address of the machine it is running on - assuming it also runs the server. Obviously this won't work in WASM as browser does not provide method to obtain local machine address.
The `simple` example has a hardcoded server address for that case.

**Comment by smokku** [comment]
Channels under WASM was already worked-out in #3 

I don't want to introduce `bevy_webgl2` dependency to `bevy_networking_turbulence` thus we've decided to keep the example in a separate repo: https://github.com/ostwilkens/arugio

**Comment by johnpmayer** [comment]
Oof, this was already tread ground. Should have read the entire README.

Thanks!

**Comment by smokku** [comment]
> Oof, this was already tread ground. Should have read the entire README.

Don't feel bad - I updated the README after you submitted the issue.
So you did contribute to fixing this. :)

**Pull request closed without merging**
