### PR TITLE
Upgraded all of the dependencies (including Bevy).

### PR DESCRIPTION
**Pull request by billyb2**
WIth this PR, bevy_networking_turbulence should now work for Bevy 0.6. I upgraded to the 2021 edition of Rust since it defaults to the v2 resolver, and doesn't break any existing code.

### CODE REVIEW

**Comment by smokku** [comment]
Could you also fix the `examples/` as they do not build ATM?

```
29 |     App::build()
   |          ^^^^^ function or associated item not found in `bevy::prelude::App`

error[E0599]: no function or associated item named `build` found for struct `bevy::prelude::App` in the current scope
```

**Comment by billyb2** [comment]
@smokku done!

**Comment by fishykins** [comment]
Love this repo, would be awesome to get it running with 0.6 :)

**Comment by smokku** [comment]
Thank you very mych @billyb2

**Comment by woelper** [comment]
Thank you very much for this, and this great library!

**Pull request merged**
